[package]
name = "readlines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.14.0"
newsapi = {version = "0.2.0", path = "../newsapi", features = ["async"]}
